require 'umakadata/models/activity'
require 'umakadata/models/linked_open_vocabulary'
require 'umakadata/models/measurement'
require 'umakadata/models/resource_uri'
require 'umakadata/models/vocabulary_prefix'
